services:
  test-db:
    image: postgres
    restart: always
    container_name: proslusha
    ports:
      - '6666:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test